Update cd-apply.yml for Azure Pipelines

diff --git a/getting-started/kubernetes/infrastructure/cd-apply.yml b/getting-started/kubernetes/infrastructure/cd-apply.yml
--- a/getting-started/kubernetes/infrastructure/cd-apply.yml
+++ b/getting-started/kubernetes/infrastructure/cd-apply.yml
@@ -19,20 +19,19 @@ stages:
   jobs:
     - job: PlanAndApply
       steps:
-        # - task: AzureCLI@1
-        #   displayName: Obtain credentials
-        #   inputs:
-        #     azureSubscription: 'DockerExamplesAzureConnection'
-            
-        #     scriptLocation: inlineScript
-        #     inlineScript: |
-        #       set -eu  # fail on error
-        #       subscriptionId=$(az account show --query id -o tsv)
-        #       echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
-        #       echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
-        #       echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
-        #       echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
-        #     addSpnToEnvironment: true
+        - task: AzureCLI@1
+          displayName: Obtain credentials
+          inputs:
+            azureSubscription: 'DockerExamplesAzureConnection'
+            scriptLocation: inlineScript
+            inlineScript: |
+              set -eu  # fail on error
+              subscriptionId=$(az account show --query id -o tsv)
+              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
+              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
+              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+            addSpnToEnvironment: true
         - task: AzureCLI@2
           displayName: Terraform init
           inputs:
@@ -41,16 +40,11 @@ stages:
             scriptType: 'bash'
             inlineScript: |
               set -eux  # fail on error
-              subscriptionId=$(az account show --query id -o tsv)
               terraform init \
                 -backend-config=storage_account_name=$(StateStorageAccount) \
                 -backend-config=container_name=$(StateContainerName) \
                 -backend-config=key=$(StateFileName) \
-                -backend-config=resource_group_name=$(StateResourceGroupName) \
-                -backend-config=subscription_id="$(subscriptionId)" \
-                -backend-config=tenant_id="$(tenantId)" \
-                -backend-config=client_id="$(servicePrincipalId)" \
-                -backend-config=client_secret="$(servicePrincipalKey)"    
+                -backend-config=resource_group_name=$(StateResourceGroupName)
             addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
         - task: AzureCLI@2
