Update cd-apply.yml for Azure Pipelines

diff --git a/getting-started/kubernetes/infrastructure/cd-apply.yml b/getting-started/kubernetes/infrastructure/cd-apply.yml
--- a/getting-started/kubernetes/infrastructure/cd-apply.yml
+++ b/getting-started/kubernetes/infrastructure/cd-apply.yml
@@ -22,34 +22,33 @@ stages:
         - task: AzureCLI@2
           displayName: Obtain credentials
           inputs:
-            scriptType: 'bash'
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptLocation: inlineScript
+            scriptType: 'pscore'
+            scriptLocation: 'inlineScript'
             inlineScript: |
-              set -eu  # fail on error
+              # set -eu  # fail on error
               subscriptionId=$(az account show --query id -o tsv)
-              echo "$servicePrincipalId"
-              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$SERVICEPRINCIPALID"
-              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$SERVICEPRINCIPALKEY"
-              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
-              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$TENANTID"
+              # echo "$servicePrincipalId"
+              Write-Output "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
+              Write-Output  "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$env:servicePrincipalKey"
+              Write-Output  "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$env:subscriptionId"
+              Write-Output  "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
               # export ARM_CLIENT_ID=$servicePrincipalId
               # export ARM_CLIENT_SECRET=$servicePrincipalKey
               # export ARM_SUBSCRIPTION_ID=$subscriptionId
               # export ARM_TENANT_ID=$tenantId
-
+              
               # terraform init \
               #   -backend-config=storage_account_name=$(StateStorageAccount) \
               #   -backend-config=container_name=$(StateContainerName) \
               #   -backend-config=key=$(StateFileName) \
               #   -backend-config=resource_group_name=$(StateResourceGroupName)
-
-            workingDirectory: 'getting-started/kubernetes/infrastructure'
             addSpnToEnvironment: true
+            workingDirectory: 'getting-started/kubernetes/infrastructure'
         - task: AzureCLI@2
           displayName: Terraform init
           inputs:
-            scriptType: 'bash'
+            scriptType: 'pscore'
             azureSubscription: 'DockerExamplesAzureConnection'
             scriptLocation: inlineScript
             inlineScript: |
@@ -66,7 +65,7 @@ stages:
           displayName: Terraform validate
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptType: 'bash'
+            scriptType: 'pscore'
             scriptLocation: inlineScript
             inlineScript: |
               terraform validate
@@ -75,7 +74,7 @@ stages:
           displayName: Terraform plan
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptType: 'bash'
+            scriptType: 'pscore'
             scriptLocation: inlineScript
             inlineScript: |
               terraform plan -out=tfplan \
@@ -92,7 +91,7 @@ stages:
           displayName: Terraform apply
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptType: 'bash'
+            scriptType: 'pscore'
             scriptLocation: inlineScript
             inlineScript: |
               terraform apply -auto-approve tfplan
