Update cd-apply.yml for Azure Pipelines

diff --git a/getting-started/kubernetes/infrastructure/cd-apply.yml b/getting-started/kubernetes/infrastructure/cd-apply.yml
--- a/getting-started/kubernetes/infrastructure/cd-apply.yml
+++ b/getting-started/kubernetes/infrastructure/cd-apply.yml
@@ -19,25 +19,26 @@ stages:
   jobs:
     - job: PlanAndApply
       steps:
-        - task: AzureCLI@1
-          displayName: Obtain credentials
-          inputs:
-            azureSubscription: 'DockerExamplesAzureConnection'
+        # - task: AzureCLI@1
+        #   displayName: Obtain credentials
+        #   inputs:
+        #     azureSubscription: 'DockerExamplesAzureConnection'
             
-            scriptLocation: inlineScript
-            inlineScript: |
-              set -eu  # fail on error
-              subscriptionId=$(az account show --query id -o tsv)
-              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
-              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
-              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
-              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
-            addSpnToEnvironment: true
-        - task: AzureCLI@1
+        #     scriptLocation: inlineScript
+        #     inlineScript: |
+        #       set -eu  # fail on error
+        #       subscriptionId=$(az account show --query id -o tsv)
+        #       echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+        #       echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
+        #       echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
+        #       echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+        #     addSpnToEnvironment: true
+        - task: AzureCLI@2
           displayName: Terraform init
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
             scriptLocation: inlineScript
+            scriptType: 'bash'
             inlineScript: |
               set -eux  # fail on error
               subscriptionId=$(az account show --query id -o tsv)
@@ -46,24 +47,26 @@ stages:
                 -backend-config=container_name=$(StateContainerName) \
                 -backend-config=key=$(StateFileName) \
                 -backend-config=resource_group_name=$(StateResourceGroupName) \
-                -backend-config=subscription_id="$(ARM_SUBSCRIPTION_ID)" \
-                -backend-config=tenant_id="$(ARM_TENANT_ID)" \
-                -backend-config=client_id="$(ARM_CLIENT_ID)" \
-                -backend-config=client_secret="$(ARM_CLIENT_SECRET)"    
+                -backend-config=subscription_id="$(subscriptionId)" \
+                -backend-config=tenant_id="$(tenantId)" \
+                -backend-config=client_id="$(servicePrincipalId)" \
+                -backend-config=client_secret="$(servicePrincipalKey)"    
             addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@1
+        - task: AzureCLI@2
           displayName: Terraform validate
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
+            scriptType: 'bash'
             scriptLocation: inlineScript
             inlineScript: |
               terraform validate
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@1
+        - task: AzureCLI@2
           displayName: Terraform plan
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
+            scriptType: 'bash'
             scriptLocation: inlineScript
             inlineScript: |
               terraform plan -out=tfplan \
@@ -75,16 +78,15 @@ stages:
                 -var aks-name=$(AKSName) \
                 -var resourceGroupName=$(ResourceGroupName) \
                 -var elasticPoolName=$(ElasticPoolName)
-            addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@1
+        - task: AzureCLI@2
           displayName: Terraform apply
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
+            scriptType: 'bash'
             scriptLocation: inlineScript
             inlineScript: |
               terraform apply -auto-approve tfplan
-            addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
 - stage: ConfigureEnvironment
   jobs:
