Revert changes

diff --git a/getting-started/kubernetes/infrastructure/cd-apply.yml b/getting-started/kubernetes/infrastructure/cd-apply.yml
--- a/getting-started/kubernetes/infrastructure/cd-apply.yml
+++ b/getting-started/kubernetes/infrastructure/cd-apply.yml
@@ -19,21 +19,21 @@ stages:
   jobs:
     - job: PlanAndApply
       steps:
-        - task: AzureCLI@2
+        - task: AzureCLI@1
           displayName: Obtain credentials
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
             scriptType: 'pscore'
-            scriptLocation: 'inlineScript'
+            scriptLocation: inlineScript
             inlineScript: |
-              # set -eu  # fail on error
-              $subscriptionId=az account show --query id -o tsv
-              # echo "$servicePrincipalId"
-              Write-Output "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
-              Write-Output  "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$env:servicePrincipalKey"
-              Write-Output  "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
-              Write-Output  "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
-              # export ARM_CLIENT_ID=$servicePrincipalId
+              set -eu  # fail on error
+              subscriptionId=$(az account show --query id -o tsv)
+              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
+              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
+              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$subscriptionId"
+              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
+            addSpnToEnvironment: true
+        - task: AzureCLI@1
               # export ARM_CLIENT_SECRET=$servicePrincipalKey
               # export ARM_SUBSCRIPTION_ID=$subscriptionId
               # export ARM_TENANT_ID=$tenantId
@@ -45,7 +45,6 @@ stages:
               #   -backend-config=resource_group_name=$(StateResourceGroupName)
             addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@2
           displayName: Terraform init
           inputs:
             scriptType: 'pscore'
@@ -59,22 +58,23 @@ stages:
                 -backend-config=storage_account_name=$env:StateStorageAccount `
                 -backend-config=container_name=$env:StateContainerName `
                 -backend-config=key=$env:StateFileName `
-                -backend-config=resource_group_name=$env:StateResourceGroupName
+                -backend-config=subscription_id="$(ARM_SUBSCRIPTION_ID)" \
+                -backend-config=tenant_id="$(ARM_TENANT_ID)" \
+                -backend-config=client_id="$(ARM_CLIENT_ID)" \
+                -backend-config=client_secret="$(ARM_CLIENT_SECRET)"    
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@2
+        - task: AzureCLI@1
           displayName: Terraform validate
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptType: 'pscore'
             scriptLocation: inlineScript
             inlineScript: |
               terraform validate
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@2
+        - task: AzureCLI@1
           displayName: Terraform plan
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptType: 'pscore'
             scriptLocation: inlineScript
             inlineScript: |
               terraform plan -out=tfplan `
@@ -86,15 +86,16 @@ stages:
                 -var aks-name=$env:AKSName `
                 -var resourceGroupName=$env:ResourceGroupName `
                 -var elasticPoolName=$env:ElasticPoolName
+            addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
-        - task: AzureCLI@2
+        - task: AzureCLI@1
           displayName: Terraform apply
           inputs:
             azureSubscription: 'DockerExamplesAzureConnection'
-            scriptType: 'pscore'
             scriptLocation: inlineScript
             inlineScript: |
               terraform apply -auto-approve tfplan
+            addSpnToEnvironment: true
             workingDirectory: 'getting-started/kubernetes/infrastructure'
 - stage: ConfigureEnvironment
   jobs:
